language: cpp
dist: trusty
sudo: required
compiler:
 - gcc
script:
 - mkdir build && cd build && cmake .. -DPYBIND11_PYTHON_VERSION=3 -DBUILD_QC=OFF -DPYTHON_BINDINGS=ON -DBUILD_EXAMPLES=ON && cmake --build .
 
