language: cpp
install: 
 - sudo apt-get install libeigen3-dev
 - sudo apt-get install libboost-all-dev
 - sudo apt-get install libboost-python-dev
script:
 - mkdir build && cd build && cmake ../ && cmake --build .
