language: cpp
dist: trusty
sudo: required
compiler:
 - gcc
install: 
 - sudo apt-get install libboost-all-dev
 - sudo apt-get install libboost-python-dev
script:
 - mkdir build && cd build && cmake .. -DBUILD_QC=on -DUSE_SYSTEM_EIGEN3=OFF -DPYTHON_BINDINGS=ON && cmake --build .
 
