language: cpp
dist: trusty
sudo: required
compiler:
 - gcc
install: 
 - sudo apt-get install libeigen3-dev
 - sudo apt-get install libboost-all-dev
 - sudo apt-get install libboost-python-dev
script:
 - mkdir build && cd build && cmake -DQPP_USE_STATIC_BOOST=ON .. && cmake --build .
